const ids=["balance","riskPct","entry","stop","target","leverage"];const $=id=>document.getElementById(id);const money=n=>Number.isFinite(n)?"$"+n.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):"—";const num=n=>Number.isFinite(n)?n.toLocaleString(undefined,{maximumFractionDigits:8}):"—";let direction="long";
function setDirection(v){direction=v;$("longBtn").classList.toggle("active",v==="long");$("shortBtn").classList.toggle("active",v==="short");calculate();}
function calculate(){const balance=parseFloat($("balance").value),riskPct=parseFloat($("riskPct").value),entry=parseFloat($("entry").value),stop=parseFloat($("stop").value),target=parseFloat($("target").value),leverage=parseFloat($("leverage").value);const err=$("error");err.hidden=true;err.textContent="";
if(![balance,riskPct,entry,stop].every(Number.isFinite)||balance<=0||riskPct<=0||entry<=0||stop<=0){err.textContent="Enter positive values for balance, risk, entry and stop-loss.";err.hidden=false;return;}
if(riskPct>=100){err.textContent="Risk per trade must be below 100%.";err.hidden=false;return;}if(entry===stop){err.textContent="Entry and stop-loss cannot be the same price.";err.hidden=false;return;}
if(direction==="long"&&stop>=entry){err.textContent="For a long trade, stop-loss should normally be below entry.";err.hidden=false;return;}
if(direction==="short"&&stop<=entry){err.textContent="For a short trade, stop-loss should normally be above entry.";err.hidden=false;return;}
const riskAmount=balance*riskPct/100,distance=Math.abs(entry-stop),qty=riskAmount/distance,notional=qty*entry,margin=Number.isFinite(leverage)&&leverage>0?notional/leverage:NaN,rr=Number.isFinite(target)&&target>0&&target!==entry?Math.abs(target-entry)/distance:NaN;
$("qty").textContent=num(qty);$("riskAmt").textContent=money(riskAmount);$("notional").textContent=money(notional);$("margin").textContent=money(margin);$("distance").textContent=money(distance);$("rr").textContent=Number.isFinite(rr)?rr.toFixed(2)+"R":"—";}
ids.forEach(id=>$(id).addEventListener("input",calculate));$("longBtn").addEventListener("click",()=>setDirection("long"));$("shortBtn").addEventListener("click",()=>setDirection("short"));$("reset").addEventListener("click",()=>{$("balance").value=400;$("riskPct").value=4;$("entry").value=65000;$("stop").value=64000;$("target").value=66000;$("leverage").value=50;setDirection("long");});calculate();